[package]
name = "markov"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.4.2",features = ["cargo","derive"]}
lstsq = "0.5.0"
nalgebra = "0.32.5"
num-derive = "0.4.2"
num-traits = "0.2.19"
rustworkx-core = "0.14.2"
